"""add some in order table

Revision ID: 88dba903b68a
Revises: 0faafedce855
Create Date: 2025-12-18 21:09:05.358509

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "88dba903b68a"
down_revision: Union[str, Sequence[str], None] = "0faafedce855"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "total_price", existing_type=sa.NUMERIC(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "orders", "total_price", existing_type=sa.NUMERIC(), nullable=False
    )
    # ### end Alembic commands ###
